exclude: 'node_modules|.git'
default_stages: [pre-commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: 'check_run.*'
        exclude: '.*json$|.*txt$|.*csv|.*md|.*svg'
      - id: check-yaml
      - id: no-commit-to-branch
        args: ['--branch', 'version-15', '--branch', 'version-16']
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ["--ignore-words-list", "notin"]
        exclude: 'yarn.lock|poetry.lock'
        additional_dependencies:
          - tomli

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: ['--py310-plus']

  - repo: https://github.com/agritheory/black
    rev: 951ccf4d5bb0d692b457a5ebc4215d755618eb68
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies: ['flake8-bugbear']

  - repo: https://github.com/agritheory/test_utils
    rev: v1.15.4
    hooks:
      - id: update_pre_commit_config
      - id: validate_frappe_project
      - id: validate_copyright
        files: '\.(js|ts|py|md)$'
        args: ['--app', 'check_run']
      - id: bylines
        exclude: 'README.md|CHANGELOG.md'
      - id: clean_customized_doctypes
        args: ['--app', 'check_run']
      - id: validate_customizations
      - id: patch_linters
        args: ['--app', 'check_run']
      - id: track_overrides
        args: ['--directory', '.', '--app', 'check_run', '--base-branch', 'version-15']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, vue, scss]
        exclude: |
          (?x)^(
            .*node_modules.*|
            check_run/public/dist/.*|
            check_run/public/js/lib/.*
          )$

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
