exclude: 'node_modules|.git'
default_stages: [pre-commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: 'check_run.*'
        exclude: '.*json$|.*txt$|.*csv|.*md|.*svg'
      - id: check-yaml
      - id: no-commit-to-branch
        args: ['--branch', 'version-14']
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        exclude: ^tests/
        args: ['--install-types', '--non-interactive', '--ignore-missing-imports']

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ['--ignore-words-list=notin']
        additional_dependencies:
          - tomli

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: ['--py310-plus']

  - repo: https://github.com/agritheory/black
    rev: 951ccf4d5bb0d692b457a5ebc4215d755618eb68
    hooks:
      - id: black
        args: ['--line-length', '99']

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --in-place]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies: ['flake8-bugbear']

  - repo: https://github.com/agritheory/test_utils/
    rev: v0.17.0
    hooks:
      - id: update_pre_commit_config
      - id: clean_customized_doctypes
        args: ['--app', 'check_run']
      - id: validate_customizations
      - id: validate_copyright
        files: '\.(js|ts|py|md)$'
        args: ['--app', 'check_run']
      # - id: sql_docstring_formatter

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier . --write --ignore-path .prettierignore
        language: node

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
