name: Pytest Base

on:
  workflow_call:
    inputs:
      db:
        required: true
        type: string
      branch-name:
        required: false
        type: string
        default: version-16
      python-version:
        required: false
        type: string
        default: '3.14'
      node-version:
        required: false
        type: number
        default: 24

permissions:
  contents: write
  checks: write
  issues: write
  pull-requests: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  tests:
    name: Server (${{ inputs.db }})
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MARIADB_ROOT_PASSWORD: 'root'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

      postgres:
        image: postgres:18.0
        env:
          POSTGRES_PASSWORD: travis
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Check for valid Python & Merge Conflicts
        run: |
          python -m compileall -q -f "${GITHUB_WORKSPACE}"
          if grep -lr --exclude-dir=node_modules "^<<<<<<< " "${GITHUB_WORKSPACE}"
              then echo "Found merge conflicts"
              exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          check-latest: true

      - name: Add to Hosts
        run: echo "127.0.0.1 test_site" | sudo tee -a /etc/hosts

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ inputs.db }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ inputs.db }}-
            ${{ runner.os }}-pip-

      - name: Cache yarn
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: bash ${GITHUB_WORKSPACE}/.github/helper/install.sh
        env:
          DB: ${{ inputs.db }}
          BRANCH_NAME: ${{ inputs.branch-name }}

      - name: Install Test Fixtures
        working-directory: /home/runner/frappe-bench
        run: bench execute 'check_run.tests.setup.before_test'

      - name: Run Tests
        working-directory: /home/runner/frappe-bench
        run: |
          set -o pipefail
          source env/bin/activate
          cd apps/check_run
          pytest check_run/tests/ --cov=check_run --cov-report=xml --disable-warnings -s | tee pytest-coverage.txt
        env:
          TYPE: server
          DB: ${{ inputs.db }}

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: /home/runner/frappe-bench/apps/check_run/pytest-coverage.txt
          pytest-xml-coverage-path: /home/runner/frappe-bench/apps/check_run/coverage.xml
