name: Diff Print Formats

on:
  pull_request:
    branches:
      - version-14
      - version-15
      - version-16

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  diff_print_format:
    runs-on: ubuntu-latest
    name: Diff Print Formats
    steps:
      - name: Diff Print Formats
        uses: agritheory/test_utils/actions/diff_print_format@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
