name: Pytest CI

on:
  push:
    branches:
      - version-14
      - version-15
      - version-16
  pull_request:

concurrency:
  group: check_run-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  mariadb:
    name: MariaDB
    uses: ./.github/workflows/_base-pytest.yml
    with:
      db: mariadb
      branch-name: ${{ github.base_ref || github.ref_name }}

  postgres:
    name: Postgres
    if: false # Enable when ERPNext postgres parity lands
    uses: ./.github/workflows/_base-pytest.yml
    with:
      db: postgres
      branch-name: ${{ github.base_ref || github.ref_name }}
