
name: Pytest CI

on:
  push:
    branches: [ version-14, version-15 ]
  pull_request:
    branches: [ version-14, version-15 ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    name: Server

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: YES
          MYSQL_ROOT_PASSWORD: 'admin'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          check-latest: true
          # cache: 'yarn'  # Should replace `Get yarn cache directory path` and `yarn-cache` steps
    
      # Uncomment if running locally, remove after local testing (already available in github actions environment)
      - name: Install Yarn
        run: npm install -g yarn

      - name: Add to Hosts
        run: echo "127.0.0.1 test_site" | sudo tee -a /etc/hosts

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt', '**/pyproject.toml', '**/setup.py', '**/setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: 'echo "::set-output name=dir::$(yarn cache dir)"'

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install JS Dependencies
        run: yarn --prefer-offline

      - name: Install App Dependencies
        run: bash ${{ github.workspace }}/.github/helper/install_dependencies.sh

      - name: Install Bench Site and Apps
        env:
          MYSQL_HOST: 'localhost'
          MYSQL_PWD: 'admin'
        run: |
          bash ${{ github.workspace }}/.github/helper/install.sh

      - name: Run Tests
        working-directory: /home/runner/frappe-bench
        run: |
          source env/bin/activate
          pytest ./apps/check_run/check_run/tests/ --disable-warnings -s
